{{- if and .Values.name (not .Values.projects) }}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  labels:
  {{- include "project-config-connector.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end  }}
  {{- with .Values.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}  
  {{- end  }}
  name: {{ required "Projec name is required" .Values.name | quote }}
spec:
  name: {{ default .Values.name .Values.projectName | quote }}
  {{- if .Values.billingAccountRef }}
  billingAccountRef:
    {{- with .Values.billingAccountRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
    {{- end }}
    {{- end }}
  {{- if .Values.folderRef }}
  folderRef:
    {{- with .Values.folderRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
    {{- end }}
    {{- end }}
  {{- if .Values.organizationRef }}
  organizationRef:
  {{- with .Values.organizationRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.resourceID }}
  resourceID: {{ .Values.resourceID | quote }}
  {{- end }}

{{- if $.Values.services }}
{{- range $service := .Values.services.list  }}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    {{- if $.Values.services.protection }}
    cnrm.cloud.google.com/deletion-policy: {{ $.Values.services.protection.deletionPolicy | default "abandon"  | quote }}
    cnrm.cloud.google.com/disable-dependent-services: {{ $.Values.services.protection.disableDependentServices | default "false" | quote }}
    {{- else }}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    {{- end }}
  name: {{ printf "%s-%s" $service $.Values.name | replace "_" "-" | replace "." "-" | trunc 64  }}
spec:
  resourceID: {{ $service }}
  projectRef:
    name: {{ $.Values.name | quote }}

{{- end  }}
{{- end  }}
{{- end  }}

