{{- if and .Values.projects (not .Values.name) }}
{{- range $name, $project := .Values.projects  }}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  labels:
  {{- include "project-config-connector.labels" $ | nindent 4 }}
  {{- if $project.labels }}
    {{- toYaml $project.labels | nindent 4 }}
  {{- end  }}
  {{- if $.Values.labels }}
    {{- toYaml $.Values.labels | nindent 4 }}
  {{- end  }}
  {{- if or $.Values.annotations $project.annotations  }}
  annotations:
  {{- if $.Values.annotations }}
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end  }}
  {{- if $project.annotations }}
    {{- toYaml $project.annotations | nindent 4 }}
  {{- end  }}   
  {{- end  }}
  name: {{ required "Projec name is required" $name | quote }}
spec:
  name: {{ default $name $project.projectName | quote }}
  {{- if $project.billingAccountRef }}
  billingAccountRef:
    {{- with $project.billingAccountRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
    {{- end }}
    {{- end }}
  {{- if $project.folderRef }}
  folderRef:
    {{- with $project.folderRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
    {{- end }}
  {{- end }}
  {{- if $project.organizationRef }}
  organizationRef:
  {{- with $project.organizationRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
  {{- end }}
  {{- end }}
  {{- if $project.resourceID }}
  resourceID: {{ $project.resourceID | quote }}
  {{- end }}

{{- if $project.services }}
{{- range $service := $project.services.list  }}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    {{- if $project.services.protection }}
    cnrm.cloud.google.com/deletion-policy: {{ $project.services.protection.deletionPolicy | default "abandon"  | quote }}
    cnrm.cloud.google.com/disable-dependent-services: {{ $project.services.protection.disableDependentServices | default "false" | quote }}
    {{- else }}
    cnrm.cloud.google.com/deletion-policy: "abandon"
    cnrm.cloud.google.com/disable-dependent-services: "false"
    {{- end }}
  name: {{ printf "%s-%s" $service $name | replace "_" "-" | replace "." "-" | trunc 64  }}
spec:
  resourceID: {{ $service }}
  projectRef:
    name: {{ $name | quote }}
{{- end  }}
{{- end  }}
{{- end  }}
{{- end  }}


