#-- Optional. Default labels attached to each resource
labels: {}
#-- Optional. Default annotations attached to each resource
annotations: {}

#-- Default values applied to each bucket. Can be overridden on specific bucket level.
default:
  spec:
#-- Optional. Immutable. The bucket's autoclass configuration.
    autoclass: {}
#-- Required*. Boolean. Immutable. While set to true, autoclass automatically transitions objects in your bucket to appropriate storage classes based on each object's access pattern.
      # enabed: True
#-- Optional. Boolean. DEPRECATED. Please use the `uniformBucketLevelAccess` field as this field has been renamed by Google. The `uniformBucketLevelAccess` field will supersede this field. Enables Bucket PolicyOnly access to a bucket.
    bucketPolicyOnly: null
#-- Optional. List. The bucket's Cross-Origin Resource Sharing (CORS) configuration. Will be added to specific bucket level Cors.
    cors: []
#-- The value, in seconds, to return in the Access-Control-Max-Age header used in preflight responses.
      # - maxAgeSeconds: integer
#-- The list of HTTP methods on which to include CORS response headers, (GET, OPTIONS, POST, etc) Note: "*" is permitted in the list of methods, and means "any method".
#         method:
#         - string
# #-- The list of Origins eligible to receive CORS response headers. Note: "*" is permitted in the list of origins, and means "any Origin".
        # origin:
        # - string
#-- The list of HTTP headers other than the simple response headers to give permission for the user-agent to share across domains.
        # responseHeader:
        # - string
#-- The bucket's custom location configuration, which specifies the individual regions that comprise a dual-region bucket. If the bucket is designated a single or multi-region, the parameters are empty.        
    customPlacementConfig: {}
#-- Immutable. The list of individual regions that comprise a dual-region bucket. See the docs for a list of acceptable regions. Note: If any of the data_locations changes, it will recreate the bucket.
      # dataLocations:
      # - string
#-- The bucket's encryption configuration.
    encryption: {}
      # kmsKeyRef:
#-- Allowed value: The `selfLink` field of a `KMSCryptoKey` resource.
        # external: string
#-- Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
        # name: string
#-- Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
        # namespace: string
#-- Optional.  The bucket's Lifecycle Rules configuration.         
    lifecycleRule: []
#-- Required.  The Lifecycle Rule's action configuration. A single block of this type is supported.
#       - action:
# #-- Optional. The target Storage Class of objects affected by this Lifecycle Rule. Supported values include: MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE.      
          # storageClass: string
#-- Required. The type of the action of this Lifecycle Rule. Supported values include: Delete, SetStorageClass and AbortIncompleteMultipartUpload.          
          # type: string
#-- Required. The Lifecycle Rule's condition configuration          
        # condition:
#-- Optional. Minimum age of an object in days to satisfy this condition.      
          # age: integer
#-- Optional. Creation date of an object in RFC 3339 (e.g. 2017-06-13) to satisfy this condition.          
          # createdBefore: string
#-- Optional. Creation date of an object in RFC 3339 (e.g. 2017-06-13) to satisfy this condition.          
          # customTimeBefore: string
#-- Optional. Number of days elapsed since the user-specified timestamp set on an object.          
          # daysSinceCustomTime: integer
#-- Optional. Number of days elapsed since the noncurrent timestamp of an object. This condition is relevant only for versioned objects.         
          # daysSinceNoncurrentTime: integer
#-- Optional. One or more matching name prefixes to satisfy this condition.          
          # matchesPrefix:
          # - string
#-- Optional. Storage Class of objects to satisfy this condition. Supported values include: MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE, STANDARD, DURABLE_REDUCED_AVAILABILITY.          
          # matchesStorageClass:
          # - string
#-- Optional. One or more matching name suffixes to satisfy this condition.          
          # matchesSuffix:
          # - string
#-- Optional. Creation date of an object in RFC 3339 (e.g. 2017-06-13) to satisfy this condition.          
          # noncurrentTimeBefore: string
#-- Optional. Relevant only for versioned objects. The number of newer versions of an object to satisfy this condition.          
          # numNewerVersions: integer
#-- Optional. Optional. Match to live and/or archived objects. Unversioned buckets have only live objects. Supported values include: "LIVE", "ARCHIVED", "ANY".          
          # withState: string
#-- Optional. String. Immutable. The Google Cloud Storage location.
    location: null
#-- Optional. The bucket's Access & Storage Logs configuration.    
    logging: {}
#-- Required. The bucket that will receive log objects
      # logBucket: string
#-- Optional. The object prefix for log objects. If it's not provided, by default Google Cloud Storage sets this to this bucket's name.
      # logObjectPrefix: string
#-- Optional. String. Prevents public access to a bucket.
    publicAccessPrevention: null
#-- Optional. Boolean. Enables Requester Pays on a storage bucket.    
    requesterPays: False
#-- Optional. Boolean. Whether or not to automatically apply an eventBasedHold to new objects added to the bucket.    
    # defaultEventBasedHold: null
#-- Optional. Configuration of the bucket's data retention policy for how long objects in the bucket should be retained.
    retentionPolicy: {}
#-- Optional. If set to true, the bucket will be locked and permanently restrict edits to the bucket's retention policy. Caution: Locking a bucket is an irreversible action.
      # isLocked: boolean
#-- Required. The period of time, in seconds, that objects in the bucket must be retained and cannot be deleted, overwritten, or archived. The value must be less than 3,155,760,000 seconds.
      # retentionPeriod: integer   
#-- Optional. String. The Storage Class of the new bucket. Supported values include: STANDARD, MULTI_REGIONAL, REGIONAL, NEARLINE, COLDLINE, ARCHIVE.
    storageClass: null
#-- Optional. Enables uniform bucket-level access on a bucket.    
    # uniformBucketLevelAccess: Boolean
#-- Optional: The bucket's Versioning configuration.
    versioning: {}
#-- Required*. While set to true, versioning is fully enabled for this bucket.
      # enabled: Boolean
#-- Optional. Configuration if the bucket acts as a website.
    website: {}
#-- Optional. Behaves as the bucket's directory index where missing objects are treated as potential directories.
      # mainPageSuffix: string
#-- Optional. The custom object to return when a requested resource is not found.
      # notFoundPage: string

#-- Map of buckets to create.
# -- Fields under each bucket in map are coresponding to above defaults.
buckets: {}
#-- Required. First level key represents nume of signle bucket. Bucket names must be globally unique. 
  # my-first-bucket:
#-- Optional. Bucket labels
    # labels: {}
#-- Optional. Bucket annotations
    # annotations: {}
#-- Optional. Assign roles to the bucket for all members from list. For more detail check .Values.IAM
    # IAM: {}
#-- Optional. Bucket specification. Following map overrides  default values. If field has no description, check .Values.default.spec
    # spec: {}
    #   location: string
    #   # autoclass:
    #   #   enabled: Boolean
    #   cors:
    #   - maxAgeSeconds: integer
    #     method:
    #     - string
    #     origin:
    #     - string
    #     responseHeader:
    #     - string
    #   customPlacementConfig:
    #     dataLocations:
    #     - string
    #   defaultEventBasedHold: boolean
    #   encryption:
    #     kmsKeyRef:
    #       external: string
    #       name: string
    #       namespace: string
    #   lifecycleRule:
    #     - action:
    #         storageClass: string
    #         type: string
    #       condition:
    #         age: integer
    #         createdBefore: string
    #         customTimeBefore: string
    #         daysSinceCustomTime: integer
    #         daysSinceNoncurrentTime: integer
    #         matchesPrefix:
    #         - string
    #         matchesStorageClass:
    #         - string
    #         matchesSuffix:
    #         - string
    #         noncurrentTimeBefore: string
    #         numNewerVersions: integer
    #         withState: string
    #   logging:
    #     logBucket: string
    #     logObjectPrefix: string
    #   publicAccessPrevention: inherited
#-- Optional. Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default.      
      # resourceID: string
      # requesterPays: boolean
      # retentionPolicy:
      #   isLocked: boolean
      #   retentionPeriod: integer
      # storageClass: string
      # versioning:
      #   enabled: boolean
      # website:
      #   mainPageSuffix: string
      #   notFoundPage: string
  
#-- Optional. Assign roles to all buckets for all members from list
IAM: {}
#-- Required*. Map where keys represent gcp bucket related roles and lists includes all impacet accounts  
#  <bucketRole>:
#    - <accountType>:<account>
# example:
#   storage.objectCreator:
#     - user:user@example.com
#     - serviceAccount:serviceaccount@example.com
#   storage.objectViewer:
#     - user:user@example.com
#     - serviceAccount:serviceaccount@example.com
#   storage.objectAdmin:
#     - user:user@example.com
#     - serviceAccount:serviceaccount@example.com
#   storage.admin:
#     - user:user@example.com
#     - serviceAccount:serviceaccount@example.com
