---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ required "kubernetesSA.name is required" .Values.kubernetesSA.name | toString |   replace "_" "-" | replace "." "-" | trunc 253 | lower | printf "%s-%s" "wli"  }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    {{- if .Values.iamSA.create }}
    name: {{ required ".Values.iamSA.name is required " .Values.iamSA.name  }}
    {{- else  }}
    external:  {{ required ".Values.iamSA.external is required " .Values.iamSA.external | quote  }}
    {{- end }}
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: 'serviceAccount:{{ $.Values.kubernetesSA.projectID }}.svc.id.goog[{{ $.Values.kubernetesSA.namespace | default $.Release.Namespace }}/{{ required ".Values.kubernetesSA.name is required" $.Values.kubernetesSA.name }}]'
