{{- if .Values.kubernetesSA.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.kubernetesSA.annotations  }}
  annotations:
    {{- toYaml . | nindent 4 }}  
  {{- end  }}
  {{- with .Values.kubernetesSA.labels  }}
  labels:
    {{- toYaml . | nindent 4 }}  
  {{- end  }}
  name: {{ required "kubernetesSA.name is required" .Values.kubernetesSA.name | toString |   replace "_" "-" | replace "." "-" | trunc 253 | lower  }}
  namespace: {{ .Values.kubernetesSA.namespace | default .Release.Namespace }}
{{- end }}
