apiVersion: v2
name: folder-config-connector
description: GCP Folder
type: application
version: 0.0.1

keywords:
  - folder
  - GCP
  - config connector

home: 3cloudarch.com
sources:
  - https://cloud.google.com/config-connector/docs/reference/resource-docs/resourcemanager/folder

maintainers: 
  - name: Karol Cienkosz
    email: karol@cienkosz.com
