{{- if and .Values.folders (not .Values.name) }}
{{- range $name, $folder := .Values.folders  }}
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  labels:
  {{- include "folder-config-connector.labels" $ | nindent 4 }}
  {{- if $folder.labels }}
    {{- toYaml $folder.labels | nindent 4 }}
  {{- end  }}
  {{- if $.Values.labels }}
    {{- toYaml $.Values.labels | nindent 4 }}
  {{- end  }}
  {{- if or $.Values.annotations $folder.annotations  }}
  annotations:
  {{- if $.Values.annotations }}
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end  }}
  {{- if $folder.annotations }}
    {{- toYaml $folder.annotations | nindent 4 }}
  {{- end  }}   
  {{- end  }}
  name: {{ required "Folder name is required" $name | quote }}
spec:
  displayName: {{ required "Folder displayName is required" $folder.displayName | quote }}
  {{- if $folder.folderRef }}
  folderRef:
    {{- with $folder.folderRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
    {{- end }}
  {{- end }}
  {{- if $folder.organizationRef }}
  organizationRef:
  {{- with $folder.organizationRef }}
    external: {{ .external | default nil | quote }}
    name: {{ .name | default nil | quote }}
    namespace: {{ .namespace | default nil | quote }}
  {{- end }}
  {{- end }}
  {{- if $folder.resourceID }}
  resourceID: {{ $folder.resourceID | quote }}
  {{- end }}
{{- end  }}
{{- end  }}
